backend:
  name: github
  repo: srifimohamed2006-dev/Repository-name
  branch: main
  base_url: https://idyllic-tapioca-349e51.netlify.app
  auth_endpoint: api/auth

media_folder: "assets/img/uploads"
public_folder: "/assets/img/uploads"

locale: "ar"

collections:
  - name: "منتجات"
    label: "منتجات"
    label_singular: "منتج"
    files:
      - file: "data/products.json"
        label: "منتجات"
        name: "منتجات"
        fields:
          - label: "منتجات"
            name: "منتجات"
            widget: "list"
            summary: "{{fields.name}} — {{fields.price}} {{fields.currency}}"
            fields:
              - { label: "المعرف (رقم فريد, لا يتكرر)", name: "id", widget: "number", value_type: "int" }
              - { label: "اسم المنتج", name: "name", widget: "string" }
              - label: "فئة"
                name: "category"
                widget: "select"
                options:
                  - { label: "الجمال", value: "beauty" }
                  - { label: "إلكترونيات", value: "electronics" }
                  - { label: "ملابس", value: "clothes" }
                  - { label: "المنزل", value: "home" }
                  - { label: "منتجات ترفيهية", value: "ترفيه" }
              - label: "دولة"
                name: "country"
                widget: "select"
                options:
                  - { label: "مصر", value: "EG" }
                  - { label: "المملكة العربية السعودية", value: "SA" }
                  - { label: "الإمارات العربية المتحدة", value: "AE" }
                  - { label: "العراق", value: "IQ" }
                  - { label: "عمان", value: "OM" }
              - { label: "السعر", name: "price", widget: "number" }
              - { label: "العملة (مثال: ج.م / ر.س)", name: "currency", widget: "string" }
              - { label: "صورة المنتج", name: "image", widget: "string" }
              - { label: "رابط الشراء (من تاجر)", name: "link", widget: "string" }
              - { label: "وصف المنتج", name: "description", widget: "text" }

  - name: "إعدادات"
    label: "مراجعة"
    files:
      - file: "data/settings.json"
        label: "المأكولات والطعام"
        name: "إعدادات"
        fields:
          - { label: "اسم المتجر", name: "shopName", widget: "string" }
          - { label: "لون الخلفية البسيط (الهيدر/البطاقات)", name: "colorInk", widget: "color" }
          - { label: "لون الخلفية الفاتح (الأساسي)", name: "colorCream", widget: "color" }
          - { label: "اللون الذهبي الأساسي", name: "colorGold", widget: "color" }
          - { label: "اللون الذهبي الفاتح", name: "colorGold2", widget: "color" }
          - { label: "لون مكمل (الأسعار)", name: "colorMaroon", widget: "color" }
